### ISSUE TITLE
🚧   Wiki: fill existing content

### ISSUE THREAD

**Issue by uxtothemax** [dewarian/Dating-Shreks#13]
# Fill with existing content

**Comment by ParvinBDJ** [comment]
Finished all my topics today 🔥

**Comment by ParvinBDJ** [comment]
Currently working on **Database** & **Coding standards** 🔥

**Comment by ParvinBDJ** [comment]
Done with everything I had to do. @uxtothemax & @dewarian. Will you finish your work today?

**Comment by uxtothemax** [comment]
Yess, I'll add the wireframes after styling! (and do a spellcheck ofcourse)

**Comment by ParvinBDJ** [comment]
Check!
