### ISSUE TITLE
🐛 Sessions error starting server.js

### ISSUE THREAD

**Issue by uxtothemax** [dewarian/Dating-Shreks#14]
**Describe the bug**
Server run until I go to http://localhost:3000/, then there's an error named 'secret option required for sessions.'

**To Reproduce**
1. Go to my house.
2. Start my computer.
(etc)
7. `npm run start` or `or npm run start :dev` or `npm run server`.
8. Go to http://localhost:3000/.

**Expected behavior**
Webpage is viewable.

**Screenshots**
![server-error-1](https://user-images.githubusercontent.com/64483507/85178488-e7096f00-b27e-11ea-99d9-615bbf3f2aa3.PNG)

After going to http://localhost:3000/ webpage:
![server-error](https://user-images.githubusercontent.com/64483507/85178725-84fd3980-b27f-11ea-9823-27e8b0581c3b.jpg)

The webpage shows this error too:
![server-error-webpage](https://user-images.githubusercontent.com/64483507/85178677-626b2080-b27f-11ea-9844-cd3dca40ac85.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Terminal: Ubuntu

**Additional context**
Added the env file to the folder before starting the server.

**Comment by bommezijn** [comment]
Pull new changes from Github.
(**pull** (retrieves new changes and merge in the local files)
or **Fetch All** (retrieve new changes, doesn't manipulate or change files (safest option))).
![image](https://user-images.githubusercontent.com/13199349/85182797-078af680-b28a-11ea-82b9-40bd173028e9.png)

Try completely restarting the server. 
(Anything after $ should be a typed prompt)
1. in terminal running node: key shortcut **ctrl + c** 
2. npm run start

Let me know if it fixes anything. If not, comment and I will try to solve it on my pc.

**Comment by uxtothemax** [comment]
Thanks for the suggestion! To be sure: I need to pull from remote dev branch to my local dev branch, right?

After doing that, the resave option error is gone, but the other still remains:

![error-resave-option-gone](https://user-images.githubusercontent.com/64483507/85185073-b3384480-b292-11ea-979d-d57415819778.PNG)

Didn't think it was relevant earlier, but better safe than sorry: before `npm run start`, I need to do `npm install` otherwise I get this error:

![old-error-new](https://user-images.githubusercontent.com/64483507/85185164-2477f780-b293-11ea-8b19-4934f6fd4d52.PNG)

**Comment by uxtothemax** [comment]
Thanks for the suggestion! To be sure: I need to pull from remote dev branch to my local dev branch, right?

After doing that, the resave option error is gone, but the other still remains:

![error-resave-option-gone](https://user-images.githubusercontent.com/64483507/85196521-0d5cf800-b2db-11ea-9f1e-80f06c25da14.PNG)

Didn't think it was relevant earlier, but better safe than sorry: before `npm run start`, I need to do `npm install` otherwise I get this error:

![server-error-webpage](https://user-images.githubusercontent.com/64483507/85196524-1057e880-b2db-11ea-9caf-a2810ba9024b.PNG)

**Comment by bommezijn** [comment]
Aha, the node_modules weren't installed after pulling `development.`

Does the issue _secret option required for sessions._ persist?

**Comment by uxtothemax** [comment]
Yeah, after npm install I still got this error:

![error-resave-option-gone](https://user-images.githubusercontent.com/64483507/85185073-b3384480-b292-11ea-979d-d57415819778.PNG)

**Comment by bommezijn** [comment]
The current issue indicates that the application wants to connect to a MongoDB database that is run locally which in turn refuses as there is no local MongoDB

**Comment by uxtothemax** [comment]
Ah, so I díd have to do something with mongoDB? Or is there another way I could start the project, so I can work on the CSS of our app?

**Comment by bommezijn** [comment]
The only thing to do with MongoDB is that it runs. The current version of the development branch relies on MongoDB to set up a session.

Check if .env still contains the following:
```
SESSION_SECRET=LUIGI
DB_NAME=shreks
MONGO_URL=mongodb+srv://bommezijn:bommezijn1@bt-dating-yddzz.mongodb.net/shreks?retryWrites=true&w=majority
```

If not, paste it in. Sadly there is no other way at this moment to work on CSS.

**Comment by uxtothemax** [comment]
Yeah check. I have the exact code in the .env. Unfortunately. still the same result...

**Comment by uxtothemax** [comment]
.....................................................env
