### ISSUE TITLE
🐛 Filter on single movie or more than two

### ISSUE THREAD

**Issue by bommezijn** [dewarian/Dating-Shreks#18]
**Describe the bug**
When filtering users on movies, it will only show users when filtering on two films. If you filter on a single or more than two movies, the response will be 'no matches found.'.

**To Reproduce**
go to branch topic-MVC either with a GUI or via terminal
```
$ git checkout topic-MVC
```
1. Run  `npm run start`
2. navigate to [localhost 3000](HTTP:localhost:3000)
3. Create a user, select movies
4. Click on the link 'Go to users'
5. try to filter on one movie or more than 2.

**Expected behavior**
Filters users based on the number of movies selected.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Browser: Chtome
 - Version Version 83.0.4103.97 (Official Build) (64-bit)

**Additional context**
Not immediately important

**Comment by ParvinBDJ** [comment]
Hey Nathan. I opened up your code and ran into the same problem. Only I didn't think it was this big of an issue being that the user has to fill in 2 movies too. Maybe, the 2 movies filled in by the user have to be automatically required. Also, I think this problem isn't too big of a problem right now. 

Maybe the fast answer, for now, might be to just to include that 2 movies are required for it to work, like this:

<img width="705" alt="Schermafbeelding 2020-06-21 om 12 10 14" src="https://user-images.githubusercontent.com/55492595/85221948-3dc69400-b3b8-11ea-9a79-8aab68fb3f87.png">
