### ISSUE TITLE
🐛 Bug: _id not Found

### ISSUE THREAD

**Issue by ParvinBDJ** [dewarian/Dating-Shreks#19]
**Describe the bug**
The process on our website works perfectly fine until you delete your account and try to make a new account. You will get the error `TypeError: Cannot read property '_id' of null` and you go the route: `localhost:3000/name` which isn't a route which actually works. It's a render.

**To Reproduce**
1. Install the repository and run: `npm install`
2. Fill in your name and then fill in your movie preferences
3. Delete your session or account 
4. You will be redirected to the homepage. Here fill in your name again
5. See error

**Expected behavior**
The browser should go to the route:` localhost:3000/name` and in the terminal, there should be this problem:
```
TypeError: Cannot read property '_id' of null
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/controller/homeController.js:62:37
    at executeCallback (/Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
    at handleCallback (/Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/operations/find_one.js:29:9
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/utils.js:731:5
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/cursor.js:251:9
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/core/cursor.js:745:9
    at handleCallback (/Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/core/cursor.js:31:5)
    at /Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/core/cursor.js:689:38
    at Cursor._endSession (/Users/gebruiker/Downloads/Dating-Shreks-topic-mvc/node_modules/mongodb/lib/core/cursor.js:394:7)
```

**Screenshots**
<img width="1280" alt="Schermafbeelding 2020-06-21 om 12 22 46" src="https://user-images.githubusercontent.com/55492595/85222242-ec1f0900-b3b9-11ea-96e0-25d74f731db0.png">

**Desktop (please complete the following information):**
 - OS: **10.15.3 (19D76)**
 - Browser **Chrome**
 - Version **83.0.4103.97**

**Additional context**
💡 NOTE: SOMETIMES IT DOESN'T HAPPEN

**Comment by bommezijn** [comment]
After changing module getHome from res.render('name') to res.render('/') it now happens after creating 2 new users instead of 1 new user.

**Comment by ParvinBDJ** [comment]
Haha nice! I think it's just a bug which is very hard to find.... Because it works sometimes and the other time it crashes. I think it has something to do with MongoDB or the sessions... Maybe it is just outside of our reacht? 😞
