### ISSUE TITLE
🚧   Clean up development branch

### ISSUE THREAD

**Issue by bommezijn** [dewarian/Dating-Shreks#28]
## ISSUE

 The branch has two view(s) folders
## DESCRIPTION
The solution, remove the views folder. But to do this, we first have to check if everything is identical. @uxtothemax changes success.handlebars with the CSS. 

We have to be careful about this.

**Comment by uxtothemax** [comment]
Hmm my changes to the handlebars files in views didn't get through or were later overwritten... I could push these again?

**Comment by bommezijn** [comment]
Welp sorry, but yea you can just push the `succes.handlebars` just make sure you fetch and place the file in 'View' before you single file push it

**Comment by uxtothemax** [comment]
Okay, I did that. But I feel like View is somehow missing some files now, is that right?

**Comment by bommezijn** [comment]
Solved the issue, can you confirm?

**Comment by ParvinBDJ** [comment]
I ran it without the views and everything was working.

**Comment by uxtothemax** [comment]
All good!
