### ISSUE TITLE
🚧   Fix the READ.me

### ISSUE THREAD

**Issue by ParvinBDJ** [dewarian/Dating-Shreks#8]
# Fix Readme
## Description
We need to show more of the app. Put in screenshots. Describe the app. And show off with the topics we all worked so hard on. 🔥🔥🔥🔥🔥🔥🔥

**Comment by ParvinBDJ** [comment]
I think @dewarian is going to work on this, good luck!

**Comment by bommezijn** [comment]
updated readme
